name: 'badge-generator'
description: 'Generate and save custom Shields.io badges directly from your GitHub Actions workflow.'
author: 'Ernane Ferreira'

inputs:
  name:
    description: 'The right-hand side value of the badge (e.g. "98.7%").'
    required: true

  prefix:
    description: 'The left-hand label of the badge (e.g. "coverage"). Optional.'
    required: false
    default: ''

  icon:
    description: 'Optional logo icon from Shields.io (e.g. "jest", "github", "npm").'
    required: false
    default: ''

  color:
    description: 'The background color of the badge (e.g. "green", "blue", "#ffaa00").'
    required: false
    default: 'blue'

  style:
    description: 'Badge style (flat, flat-square, plastic, for-the-badge, social).'
    required: false
    default: 'flat'

  path:
    description: 'Output file path for the generated badge SVG (e.g. "badges/coverage.svg").'
    required: true

  labelColor:
    description: 'Optional background color for the left-side label (e.g. "#333").'
    required: false
    default: ''

  logoColor:
    description: 'Optional color for the logo icon (e.g. "white", "#ffcc00").'
    required: false
    default: ''

  link:
    description: 'Optional URL or comma-separated URLs to make the badge clickable.'
    required: false
    default: ''

  cacheSeconds:
    description: 'Optional Shields.io cache duration in seconds.'
    required: false
    default: ''

  badge_branch:
    description: 'The branch where the badge should be committed (e.g. badge-generator).'
    required: false
    default: 'badge-generator'

  main_branch:
    description: 'The default branch of the repository (e.g. main).'
    required: false
    default: 'main'

  github_token:
    description: 'GitHub token to post comments on pull requests.'
    required: false
    default: ''

outputs: {}

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'award'
  color: 'blue'
